# documentation: https://docs.openclaw.ai
# slogan: Personal AI assistant for WhatsApp, Telegram, Discord and more
# tags: ai,assistant,chatbot,whatsapp,telegram,discord,automation,llm,claude,openai
# logo: svgs/openclaw.svg
# port: 18789

services:
  openclaw:
    image: "node:22-bookworm"
    working_dir: /app
    command: >
      bash -c "
        if [ ! -d /app/node_modules ]; then
          echo 'First run: Installing OpenClaw...';
          git clone --depth 1 https://github.com/openclaw/openclaw.git /tmp/openclaw &&
          cp -r /tmp/openclaw/* /app/ &&
          corepack enable &&
          pnpm install &&
          pnpm build &&
          pnpm ui:install &&
          pnpm ui:build;
        fi;
        node dist/index.js gateway --bind lan --port 18789
      "
    environment:
      - NODE_ENV=production
      - HOME=/home/node
      - TERM=xterm-256color
      # Gateway Configuration
      - OPENCLAW_GATEWAY_BIND=lan
      - OPENCLAW_GATEWAY_PORT=18789
      - OPENCLAW_GATEWAY_TOKEN=${SERVICE_PASSWORD_OPENCLAW}
      # Data Paths
      - OPENCLAW_CONFIG_PATH=/data/.openclaw/openclaw.json
      - OPENCLAW_STATE_DIR=/data/.openclaw
      - XDG_CONFIG_HOME=/data/.openclaw
      # Model Authentication (set at least one)
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Channel: Telegram
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      # Channel: Discord
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
      # Channel: Slack
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-}
      # Browser Integration
      - OPENCLAW_BROWSER_ENABLED=${OPENCLAW_BROWSER_ENABLED:-true}
      - OPENCLAW_BROWSER_URL=http://openclaw-browser:9222
      # Redis Cache
      - REDIS_URL=redis://openclaw-redis:6379
      # Optional: Web Search
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY:-}
      # Optional: Gmail
      - GOG_KEYRING_PASSWORD=${GOG_KEYRING_PASSWORD:-}
    volumes:
      - openclaw-app:/app
      - openclaw-config:/data/.openclaw
      - openclaw-workspace:/data/openclaw
    depends_on:
      openclaw-redis:
        condition: service_healthy
      openclaw-browser:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18789/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openclaw.entrypoints=http"
      - "traefik.http.services.openclaw.loadbalancer.server.port=18789"

  openclaw-redis:
    image: "redis:7-alpine"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - openclaw-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  openclaw-browser:
    image: "zenika/alpine-chrome:with-node"
    command: chromium-browser --headless --disable-gpu --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
    environment:
      - CHROME_BIN=/usr/bin/chromium-browser
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  openclaw-app:
  openclaw-config:
  openclaw-workspace:
  openclaw-redis-data:
